USE [ashish]
GO

/****** Object:  Table [dbo].[Inventory]    Script Date: 03-10-2020 14:05:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Inventory](
	[ItemID] [int] IDENTITY(1,1) NOT NULL,
	[ItemName] [varchar](255) NOT NULL,
	[Description] [varchar](255) NULL,
	[Price] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ItemID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

